# Generated by Django 4.2.3 on 2023-07-31 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_candidato', models.CharField(max_length=100)),
                ('faixa_salarial', models.IntegerField(choices=[(1, 'Até 1.000'), (2, 'De 1.000 a 2.000'), (3, 'De 2.000 a 3.000'), (4, 'Acima de 3.000')])),
                ('escolaridade_minima', models.IntegerField(choices=[(1, 'Ensino Fundamental'), (2, 'Ensino Médio'), (3, 'Tecnólogo'), (4, 'Ensino Superior'), (5, 'Pós / MBA / Mestrado'), (6, 'Doutorado')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vagas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('faixa_salarial', models.IntegerField(choices=[(1, 'Até 1.000'), (2, 'De 1.000 a 2.000'), (3, 'De 2.000 a 3.000'), (4, 'Acima de 3.000')])),
                ('escolaridade_minima', models.IntegerField(choices=[(1, 'Ensino Fundamental'), (2, 'Ensino Médio'), (3, 'Tecnólogo'), (4, 'Ensino Superior'), (5, 'Pós / MBA / Mestrado'), (6, 'Doutorado')])),
                ('requisitos', models.TextField()),
                ('candidatosInscritos', models.IntegerField(default=0)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vagas', to='app_vagas.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Vagas_aplicadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontuacao', models.IntegerField(default=0)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_vagas.candidato')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vagas_aplicadas', to='app_vagas.vagas')),
            ],
        ),
    ]
