# Generated by Django 4.2.3 on 2023-08-02 21:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_vagas", "0006_alter_vagas_aplicadas_vaga"),
    ]

    operations = [
        migrations.AddField(
            model_name="vagas",
            name="data_criacao",
            field=models.DateField(
                default=datetime.datetime(2023, 8, 2, 18, 35, 18, 397599)
            ),
        ),
        migrations.AddField(
            model_name="vagas_aplicadas",
            name="data_criacao",
            field=models.DateField(
                default=datetime.datetime(2023, 8, 2, 18, 35, 18, 397599)
            ),
        ),
    ]
