# Generated by Django 4.2.3 on 2023-08-02 21:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_vagas", "0007_vagas_data_criacao_vagas_aplicadas_data_criacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vagas",
            name="data_criacao",
            field=models.DateField(
                verbose_name=datetime.datetime(2023, 8, 2, 18, 36, 19, 237487)
            ),
        ),
        migrations.AlterField(
            model_name="vagas_aplicadas",
            name="data_criacao",
            field=models.DateField(
                verbose_name=datetime.datetime(2023, 8, 2, 18, 36, 19, 238481)
            ),
        ),
    ]
